app/controllers/controllerCars.py
from flask import Blueprint
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from app import db, bcrypt
from app.forms.carForm import CarForm
from app.models.modelCars import Car, CarDataValue, CarData
from flask_login import current_user, login_required
from app.controllers.utilsCars import *

cars = Blueprint('cars', __name__)


@cars.route('/auto', methods=['GET', 'POST'])
@login_required
def auto():
    return render_template('lista_auto.html', title='Auto',
                           car=current_user.cars)

@cars.route("/car/new_car", methods=['GET', 'POST'])
@login_required
def new_car():
    form = CarForm()
    if form.validate_on_submit():
       car = Car(name=form.name.data, fuel=form.fuel.data,
                 matriculation=form.matriculation.data, author=current_user)
       db.session.add(car)
       AddCarValueToDb(car,form)
       db.session.commit()
       flash('I dati della tua auto sono stati salvati !', 'success')
       return redirect(url_for('main.home'))
    return render_template('new_car.html', title='New Car',
                            form=form, legend='Nuova Auto')

app/controllers/controllerUsers.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app.forms.userForm import LoginForm, RegistrationForm
from app import db, login_manager, bcrypt
from app.models.modelUsers import User, UserLogin
from app.models.modelCars import Car

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data)
        db.session.add(user)
        db.session.commit()
        user_login = UserLogin(email=form.email.data, password=hashed_password, id_user=user.id)
        db.session.add(user_login)
        db.session.commit()
        flash('Il tuo account è stato creato! Ora puoi effettuare il log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        userLogin = UserLogin.query.filter_by(email=form.email.data).first()
        if userLogin and bcrypt.check_password_hash(userLogin.password, form.password.data):
            user = User.query.filter_by(id=userLogin.id).first()
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Il login non è andato a buon fine. Controlla email e password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

app/templates/home.html
{% extends "layout.html" %}
{%block content%}
 <div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-8 text-left"> 
      <h1>Benvenuto su <big>SaveYourCar</big></h1>
      <p>Questa Web App è indirizzata a chiunque voglia monitorare al meglio la propria auto.</p>
      <p>Registrati o effettua il login per usufruire di tutti i nostri serizi!</p>
      <hr>
      <h3></h3>
      <p></p>
    </div>
    <div class="col-sm-2 sidenav">
      <div>
		<img class="rounded mx-auto d-block" src="{{ url_for('static', filename='logo.png') }}">
      </div>
    </div>
  </div>
 </div>
{%endblock content%}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>SaveYourCar</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  </style>
</head>
<body>
 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
        <img class="icon-bar" src="{{ url_for('static', filename='logo.png') }}">
    </div>
      {% if current_user.is_authenticated %}
       <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('cars.new_car') }}">Nuova Auto</a></li>
            <li><a href="{{url_for('cars.auto') }}">Auto</a></li>
            <li><a href="#">Account</a></li>
        </ul>
       </div>
                   <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{{ url_for('users.logout') }}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
                </ul>
            </div>
      {% else %}
       <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('users.register') }}">Registrazione</a></li>
            <li><a href="#">Contatti</a></li>
        </ul>
       </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{{ url_for('users.login') }}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
      {% endif %}  
  </div>
 </nav>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>
 <footer class="container-fluid text-center">
  <p></p>
 </footer>
</body>
</html>

app/templates/lista_auto.html
{% extends "layout.html" %}
{%block content%}
 <div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-8 text-left">
        {% for car in car %}
        <div class="media content-section">
          <div>
            <h2><a class="article-title" href="#">{{ car.name }}</a></h2>
          </div>
        </div>
    {% endfor %}
    </div>
    <div class="col-sm-2 sidenav">
      <div>
		<img class="rounded mx-auto d-block" src="{{ url_for('static', filename='logo.png') }}">
      </div>
    </div>
  </div>
 </div>
{%endblock content%}

app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="#">/Hai dimenticato la password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Hai bisogno di Un Account? <a class="ml-2" href="{{ url_for('users.register') }}">Registrati Ora</a>
        </small>
    </div>
{% endblock content %}

app/templates/new_car.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
<!-- inserire immagine -->
	<form method="POST" action="">
		 {{ form.hidden_tag() }}
		 <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.fuel.label(class="form-control-label") }}
                {% if form.fuel.errors %}
                    {{ form.fuel(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.fuel.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.fuel(class="form-control form-control-lg") }}
                {% endif %}
            </div>
             <div class="form-group">
                {{ form.matriculation.label(class="form-control-label") }}
                {% if form.matriculation.errors %}
                    {{ form.matriculation(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.matriculation.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.matriculation(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.kmattuali.label(class="form-control-label") }}
                {% if form.kmattuali.errors %}
                    {{ form.kmattuali(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.kmattuali.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.kmattuali(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.dataRevisione.label(class="form-control-label") }}
                {% if form.dataRevisione.errors %}
                    {{ form.dataRevisione(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.dataRevisione.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.dataRevisione(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.kmTagliando.label(class="form-control-label") }}
                {% if form.kmTagliando.errors %}
                    {{ form.kmTagliando(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.kmTagliando.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.kmTagliando(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.dataAssicurazione.label(class="form-control-label") }}
                {% if form.dataAssicurazione.errors %}
                    {{ form.dataAssicurazione(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.dataAssicurazione.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.dataAssicurazione(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.dataBollo.label(class="form-control-label") }}
                {% if form.dataBollo.errors %}
                    {{ form.dataBollo(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.dataBollo.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.dataBollo(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.kmMedi.label(class="form-control-label") }}
                {% if form.kmMedi.errors %}
                    {{ form.kmMedi(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.kmMedi.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.kmMedi(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>





</div>
{% endblock content %}

app/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Registrati Oggi</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Hai già un Account? <a class="ml-2" href="{{ url_for('users.login') }}">Effettua il Log In</a>
        </small>
    </div>
{% endblock content %}